### ISSUE TITLE
Eventeum error: There was an error when processing a block, disposing blocksubscription

### ISSUE THREAD

**Issue by pranavt61** [eventeum/eventeum#157]
I am running the official Eventeum docker image in a docker-compose project, I am getting this continuous error every-time a block-event topic is emmited to Kafka:

```
2020-12-19 02:00:26.227 [eventeum-scheduler1] INFO  net.consensys.eventeum.chain.service.block.DefaultBlockNumberService: getStartBlockForNode - Last block number processed on node default: 7744400
eventeum_1        | 2020-12-19 02:00:26.228 [eventeum-scheduler1] INFO  net.consensys.eventeum.chain.service.block.DefaultBlockNumberService: getStartBlockForNode - Start block number for node default: 7744388
eventeum_1        | 2020-12-19 02:00:26.228 [eventeum-scheduler1] INFO  net.consensys.eventeum.chain.service.strategy.PollingBlockSubscriptionStrategy: subscribe - Starting block polling, from block 7744388
eventeum_1        | 2020-12-19 02:00:26.401 [BLOCK-DEFAULT-0] INFO  net.consensys.eventeum.chain.block.LoggingBlockListener: onBlock - New block mined. Hash: 0x815545c80f67b5d44a768992e1cc65a7c1bc67699baf412a116afed253fbc19b, Number: 7744388
eventeum_1        | 2020-12-19 02:00:26.403 [BLOCK-DEFAULT-0] INFO  net.consensys.eventeum.integration.broadcast.blockchain.KafkaBlockchainEventBroadcaster: broadcastNewBlock - Sending block message: {"id":"0x815545c80f67b5d44a768992e1cc65a7c1bc67699baf412a116afed253fbc19b","type":"BLOCK","details":{"number":7744388,"hash":"0x815545c80f67b5d44a768992e1cc65a7c1bc67699baf412a116afed253fbc19b","timestamp":1608343034,"nodeName":"default"},"retries":0}
eventeum_1        | 2020-12-19 02:00:26.410 [BLOCK-DEFAULT-0] ERROR net.consensys.eventeum.chain.service.strategy.AbstractBlockSubscriptionStrategy: onError - There was an error when processing a block, disposing blocksubscription (will be reinitialised)
eventeum_1        | java.util.concurrent.CompletionException: java.lang.NullPointerException
eventeum_1        |     at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_262]
eventeum_1        |     at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_262]
eventeum_1        |     at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1643) ~[na:1.8.0_262]
eventeum_1        |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_262]
eventeum_1        |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_262]
eventeum_1        |     at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_262]
eventeum_1        | Caused by: java.lang.NullPointerException: null
eventeum_1        |     at net.consensys.eventeum.chain.util.Web3jUtil.getSignature(Web3jUtil.java:94) ~[eventeum-core-0.9.0-RELEASE.jar!/:0.9.0-RELEASE]
eventeum_1        |     at net.consensys.eventeum.chain.util.BloomFilterUtil.getBloomBits(BloomFilterUtil.java:36) ~[eventeum-core-0.9.0-RELEASE.jar!/:0.9.0-RELEASE]
eventeum_1        |     at net.consensys.eventeum.chain.contract.DefaultContractEventProcessor.isEventFilterInBloomFilter(DefaultContractEventProcessor.java:77) ~[eventeum-core-0.9.0-RELEASE.jar!/:0.9.0-RELEASE]
eventeum_1        |     at net.consensys.eventeum.chain.contract.DefaultContractEventProcessor.processLogsForFilter(DefaultContractEventProcessor.java:66) ~[eventeum-core-0.9.0-RELEASE.jar!/:0.9.0-RELEASE]
eventeum_1        |     at net.consensys.eventeum.chain.contract.DefaultContractEventProcessor.lambda$null$0(DefaultContractEventProcessor.java:50) ~[eventeum-core-0.9.0-RELEASE.jar!/:0.9.0-RELEASE]
eventeum_1        |     at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_262]
eventeum_1        |     at net.consensys.eventeum.chain.contract.DefaultContractEventProcessor.lambda$processLogsInBlock$1(DefaultContractEventProcessor.java:50) ~[eventeum-core-0.9.0-RELEASE.jar!/:0.9.0-RELEASE]
eventeum_1        |     at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[na:1.8.0_262]
eventeum_1        |     ... 3 common frames omitted
eventeum_1        | 2020-12-19 02:00:31.376 [eventeum-scheduler1] ERROR net.consensys.eventeum.chain.service.health.NodeHealthCheckService: checkHealth - Node default is down or unsubscribed!!
eventeum_1        | 2020-12-19 02:00:31.451 [eventeum-scheduler1] INFO  net.consensys.eventeum.chain.service.block.DefaultBlockNumberService: getStartBlockForNode - Last block number processed on node default: 7744400
eventeum_1        | 2020-12-19 02:00:31.451 [eventeum-scheduler1] INFO  net.consensys.eventeum.chain.service.block.DefaultBlockNumberService: getStartBlockForNode - Start block number for node default: 7744388
eventeum_1        | 2020-12-19 02:00:31.451 [eventeum-scheduler1] INFO  net.consensys.eventeum.chain.service.strategy.PollingBlockSubscriptionStrategy: subscribe - Starting block polling, from block 7744388
eventeum_1        | 2020-12-19 02:00:31.628 [BLOCK-DEFAULT-0] INFO  net.consensys.eventeum.chain.block.LoggingBlockListener: onBlock - New block mined. Hash: 0x815545c80f67b5d44a768992e1cc65a7c1bc67699baf412a116afed253fbc19b, Number: 7744388
eventeum_1        | 2020-12-19 02:00:31.630 [BLOCK-DEFAULT-0] INFO  net.consensys.eventeum.integration.broadcast.blockchain.KafkaBlockchainEventBroadcaster: broadcastNewBlock - Sending block message: {"id":"0x815545c80f67b5d44a768992e1cc65a7c1bc67699baf412a116afed253fbc19b","type":"BLOCK","details":{"number":7744388,"hash":"0x815545c80f67b5d44a768992e1cc65a7c1bc67699baf412a116afed253fbc19b","timestamp":1608343034,"nodeName":"default"},"retries":0}
eventeum_1        | 2020-12-19 02:00:31.634 [BLOCK-DEFAULT-0] ERROR net.consensys.eventeum.chain.service.strategy.AbstractBlockSubscriptionStrategy: onError - There was an error when processing a block, disposing blocksubscription (will be reinitialised)
eventeum_1        | java.util.concurrent.CompletionException: java.lang.NullPointerException
eventeum_1        |     at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_262]
eventeum_1        |     at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_262]
eventeum_1        |     at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1643) ~[na:1.8.0_262]
eventeum_1        |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_262]
eventeum_1        |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_262]
eventeum_1        |     at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_262]
eventeum_1        | Caused by: java.lang.NullPointerException: null
eventeum_1        |     at net.consensys.eventeum.chain.util.Web3jUtil.getSignature(Web3jUtil.java:94) ~[eventeum-core-0.9.0-RELEASE.jar!/:0.9.0-RELEASE]
eventeum_1        |     at net.consensys.eventeum.chain.util.BloomFilterUtil.getBloomBits(BloomFilterUtil.java:36) ~[eventeum-core-0.9.0-RELEASE.jar!/:0.9.0-RELEASE]
eventeum_1        |     at net.consensys.eventeum.chain.contract.DefaultContractEventProcessor.isEventFilterInBloomFilter(DefaultContractEventProcessor.java:77) ~[eventeum-core-0.9.0-RELEASE.jar!/:0.9.0-RELEASE]
eventeum_1        |     at net.consensys.eventeum.chain.contract.DefaultContractEventProcessor.processLogsForFilter(DefaultContractEventProcessor.java:66) ~[eventeum-core-0.9.0-RELEASE.jar!/:0.9.0-RELEASE]
eventeum_1        |     at net.consensys.eventeum.chain.contract.DefaultContractEventProcessor.lambda$null$0(DefaultContractEventProcessor.java:50) ~[eventeum-core-0.9.0-RELEASE.jar!/:0.9.0-RELEASE]
eventeum_1        |     at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_262]
eventeum_1        |     at net.consensys.eventeum.chain.contract.DefaultContractEventProcessor.lambda$processLogsInBlock$1(DefaultContractEventProcessor.java:50) ~[eventeum-core-0.9.0-RELEASE.jar!/:0.9.0-RELEASE]
eventeum_1        |     at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[na:1.8.0_262]
eventeum_1        |     ... 3 common frames omitted
```

This is my docker-compose file:

```
version: '3'

services:
  eventeum:
    image: eventeum/eventeum:latest
    ports:
    - "8060:8060"
    depends_on:
      - mongodb
      - kafka
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      ETHEREUM_NODE_URL: https://mainnet.infura.io/v3/MY_KEY_HERE 
      ZOOKEEPER_ADDRESS: zookeeper:2181
      KAFKA_ADDRESSES: kafka:19092
      ETHEREUM_NODES_0_BLOCKSTRATEGY: PUBSUB
    networks:
      - default

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - $HOME/mongodb/data/db:/data/db
    networks:
      - default

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.1-1
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - default

  kafka:
    image: confluentinc/cp-kafka:5.0.1-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - default

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.5.1
    hostname: control-center
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:19092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    networks:
      - default
    restart: always
```
